import { SignIn, SignInButton, SignOutButton, UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
dayjs.extend(relativeTime);

const CreatePostWizard = () => {

  const { user } = useUser();

  console.log(user);

  if (!user) return null;
  
  return (
    <div className="flex w-full gap-3">
      <img 
        src={user.profileImageUrl} 
        alt="Profile Image" 
        className="h-14 w-14 rounded-full"
      />
      <input placeholder="Type some emojis" className="bg-transparent flex-grow outline-none" />
    </div>
  )
}

type PostWithAuthor = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithAuthor) => {
  const { post, author } = props;
  return (
  <div key={post.id} className="flex gap-3 p-3 border-b border-slate-400"> 
    <img src={author.profileImageUrl} alt="Profile Image" className="h-12 w-12 rounded-full" />
    <div className="flex flex-col">
      <div className="flex gap-1 text-slate-400">
        <span>{`@${author.username} ·`}</span>
        <span className="font-thin">{`${dayjs(post.createdAt).fromNow()}`}</span>
      </div>
      <span>
        {post.content}
      </span>
    </div>
  </div>
  )
}

export default function Home() {
  const user = useUser();

  const { data } = api.posts.getAll.useQuery(); //tRPC hook to run the query on the server
    
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="h-full w-full md:max-w-2xl border-x border-slate-400">
          <div className="flex border-b border-slate-400 p-4">
          {!user.isSignedIn && <SignInButton />}
          {user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="flex flex-col">
            {data?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id}/>
            ))}
          </div>
          <div><UserButton></UserButton></div>
        </div>
      </main>
    </>
  );
}
